# Generated by Django 3.0.6 on 2020-05-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('item_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_desc', models.CharField(max_length=20)),
                ('segment', models.CharField(max_length=1)),
                ('information', models.CharField(max_length=500, null=True)),
                ('percentage_alchol', models.FloatField(null=True)),
                ('temparate', models.FloatField(null=True)),
                ('item_cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productsapi.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_size_in_ml', models.FloatField()),
                ('case_sale_rate', models.FloatField()),
                ('bottle_mrp_rate', models.FloatField()),
                ('bottle_in_case', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='productsapi.ProductItem')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='productsapi.SubType'),
        ),
    ]
