# Generated by Django 3.0.6 on 2020-05-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productsapi.ProductItem'),
        ),
    ]
