# Generated by Django 3.0.6 on 2020-05-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0002_auto_20200523_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='product',
            new_name='item',
        ),
    ]
