# Generated by Django 3.0.6 on 2020-05-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0003_auto_20200523_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='item_code',
            new_name='item_id',
        ),
    ]
