# Generated by Django 3.0.6 on 2020-05-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0004_auto_20200523_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantity', to='productsapi.ProductItem'),
        ),
    ]
