# Generated by Django 3.0.6 on 2020-05-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0005_auto_20200523_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='productsapi.SubType'),
        ),
    ]
